### ISSUE TITLE
Add support to iOS simulator to the mobile client.

### ISSUE THREAD

**Issue by bchesleyEE** [mimikgit/cocoapod-MIMIKEdgeMobileClient#1]
I was working on an application that used to support the IOS simulator on my MacBook but after the addition of MIMIK, this is no longer supported.  It would be great if support for this was added.
![image](https://user-images.githubusercontent.com/57908011/106664698-6f6d2380-6573-11eb-8207-81c0d0ec49c5.png)

**Comment by mimikrb** [comment]
Unfortunately this is not possible since one of the components of MIMIKEdgeMobileClient library, edgeEngine cannot be used on a simulated platform. This is the reason why a real device is required and a simulated platform is not supported.

Please see the list of edgeEngine supported platforms at: https://developer.mimik.com/downloads/

**Comment by mimikrb** [comment]
Closing.
